Merge v1.5.1 into Mojave (#8)
* macos_compatability_check: Update current version

Pipe the output of ‘sw_vers -productVersion’ to `awk` to remove the PATCH version number.

Previous output was: 10.13.5
New output is: 10.13

* main: Update top variable

Bump from 6 to 7 to account for a new utility function

* Update colour definitions

* macos_compatability_check: $supported_ readonly

* Fix parameter expansion

* get_fix_mode_permission: Declare and assign var

* check_filevault: Use fdesetup instead of diskutil

* Initial commit

Signature file for Lockdown v1.2.0

* Add release version badge

* Update description

* Add Verification section

* Fix formatting

* Remove explicit version references from comments

* check_EFI_integrity: Rename to check_efi_integrity

* check_efi_integrity: Check if Mac has a T2 chip

If the Mac has a T2 chip skip running `eficheck`.

Should address #4

* check_firmware_password_set: Supress grep output

* macos_compatability_check: New macos_name method

This will need to be updated for each major release if the number of words in the release name changes.

Addresses #3.

* macos_compatability_check: Check if on a Mac

* macos_compatability_check: Update function description

* Update signature for v1.3.0

* Add option to bypass fix mode permission prompt

* Fix comment formatting

* main: rename force to fix_force

* Update signature for v1.3.1

* main: Remove mapfile dependency to address #6

Settings is now manually filled rather than greping the Lockdown source to dynamically fill it.

* Remove comment

* Remove Requirements section

Related to #6

* Update Usage section

* Update signature for v1.4.0

* disable_mail_remote_content: Use -bool over -int

Prefer setting true/false preferences with -bool true/false rather than -int 1/0.

* check_efi_integrity: Check ‘Model Name’ field

Rather than greping the whole output of `system_profiler SPiBridgeDataType` for the string “T2” only grep the ‘Model Name’ field.

* Add list of utility functions

* Add verify_signature

If minisign is installed then self validate Lockdown’s signature

* Update signature for v1.5.0

* Remove bash_compatability_check

Commit 061d1580342f5b5275ac88365ab4bf75559d3534 removed the dependancy of `mapfile` but I forgot to remove the  bash_compatability_check code.

Finally addresses #6.

* Fix formatting

* Update signature for v1.5.1

diff --git a/Lockdown b/Lockdown
--- a/Lockdown
+++ b/Lockdown
@@ -5,7 +5,6 @@
 #   Lockdown macOS Mojave security settings
 
 set -uo pipefail
-# -e exit if any command returns non-zero status code
 # -u prevent using undefined variables
 # -o pipefail force pipelines to fail on first non-zero status code
 
@@ -16,7 +15,8 @@ IFS=$'\n\t'
 
 ### Define Colours ###
 
-tput sgr0; # reset colors
+tput sgr0; 
+# reset colors
 
 readonly RED="$(tput setaf 1)"
 readonly RESET="$(tput sgr0)"
@@ -30,13 +30,19 @@ function usage {
   echo "Usage:"
   echo "  list         - List all settings that can be audited/ fixed"
   echo "  audit        - Audit the status of all settings (Does ${BOLD}NOT${RESET} change settings)"
-  echo "  ${RED}fix${RESET}          - Attempt to fix all settings (${BOLD}Does${RESET} change settings)"
+  echo "  ${RED}fix${RESET}  {force} - Attempt to fix all settings (${BOLD}Does${RESET} change settings)"
 
   exit 0
 }
 
 
 ### UTILITY FUNCTIONS ###
+# macos_compatability_check
+# audit
+# fix
+# mode_check
+# get_fix_mode_permission
+# verify_signature
 
 
 function macos_compatability_check {
@@ -68,22 +74,6 @@ function macos_compatability_check {
   if [ "${current_macos_version}" != "${supported_macos_version}" ]; then 
     echo "[❌] Lockdown was built for macOS ${supported_macos_name} (${supported_macos_version}.x)"
     echo "[🍺] This is macOS ${current_macos_name} (${current_macos_version})"
-    exit 1
-  fi
-}
-
-
-function bash_compatability_check {
-
-  # Check the system has at least Bash 4.x
-
-  local bash_version
-  bash_version="$(echo "${BASH_VERSION}" | awk -F '.' '{print $1}')"; 
-  
-  if [ "${bash_version}" -lt 4 ]; then 
-    echo "[❌] Sorry, this script requires Bash 4.x"
-    echo "[🍺] Current Bash version is ${BASH_VERSION}"
-    echo "[⬇️] brew install bash"
     exit 1
   fi
 }
@@ -163,6 +153,24 @@ function get_fix_mode_permission {
   else
     echo "[❌] ${USER} has chosen to quit"
     exit 1
+  fi
+}
+
+
+function verify_signature {
+  
+  # Verify Lockdown signature with minisign
+
+  if [ -x "$(command -v minisign)" ]; then
+
+    if ! minisign -Vm ./Lockdown -P "RWTiYbJbLl7q6uQ70l1XCvGExizUgEBNDPH0m/1yMimcsfgh542+RDPU" >/dev/null; then 
+      echo "[❌] Failed to validate Lockdown signature with minisign"
+      exit 1
+    fi
+
+  else
+    echo "[⚠️ ] Unable to verify Lockdown signature as minisign is not installed"
+    echo "[🍺] brew install minisign"
   fi
 }
 
@@ -317,7 +325,7 @@ function disable_mail_remote_content {
 
   audit_command="defaults read com.apple.mail-shared DisableURLLoading 2>/dev/null | grep -q '1'"
   
-  fix_command="defaults write com.apple.mail-shared DisableURLLoading -int '1'"
+  fix_command="defaults write com.apple.mail-shared DisableURLLoading -bool true"
 
   mode_check "${mode}" "${title}" "${audit_command}" "${fix_command}"
 }
@@ -436,8 +444,7 @@ function check_efi_integrity {
   audit_command="/usr/libexec/firmwarecheckers/eficheck/eficheck --integrity-check >/dev/null 2>&1"
   fix_command=''
 
-
-  if system_profiler SPiBridgeDataType | grep -q 'T2'; then 
+  if system_profiler SPiBridgeDataType | grep 'Model Name:' | grep -q 'T2'; then 
     echo "[⚠️ ] Check EFI Firmware Integrity ${RED}is not${RESET} supported by this Mac"
     return 1 
   fi
@@ -483,21 +490,20 @@ function check_firmware_password_set {
 
 function main {
 
+  verify_signature
+  # Verify Lockdown signature 
   macos_compatability_check
   # Check the system is running the supoorted version of macOS 
-  bash_compatability_check
-  # Check the system has at least Bash 4.x
 
   local cmd=${1:-"usage"}
   local settings=()
-  local all_functions
 
-  all_functions="$(grep "^function" "${0}")"
-  mapfile -t settings < <(echo "${all_functions}" \
-                      | awk '{print $2}' \
-                      | awk -v top=7 -v bottom=1 'NR<=top{next};NR>bottom+top{print line[NR%bottom]};{line[NR%bottom]=$0}')
-  # Build an array of all but the top 7 (utility functions) and bottom 1 (main) function names
-  # top NEEDS to be updated when new UTILITY functions are added
+  settings=(enable_automatic_updates enable_gatekeeper enable_firewall enable_admin_password_preferences \
+                  enable_terminal_secure_entry disable_firewall_builin_software disable_firewall_downloaded_signed\
+                  disable_ipv6 disable_mail_remote_content disable_remote_apple_events disable_remote_login \
+                  set_airdrop_contacts_only set_appstore_update_check_daily check_SIP check_kext_loading_consent \
+                  check_efi_integrity check_filevault check_firmware_password_set)
+
 
   if [[ "${cmd}" == "audit" ]]; then
 
@@ -510,8 +516,13 @@ function main {
 
   elif [[ "${cmd}" == "fix" ]]; then
 
-    # Confirm the user wants to run FIX mode
-    get_fix_mode_permission
+    local fix_force=${2:-"false"}
+
+    if [[ "${fix_force}" != "force" ]]; then
+      # Confirm the user wants to run FIX mode
+      # If "fix force" skip the prompt 
+      get_fix_mode_permission
+    fi
 
     for setting in "${settings[@]}"; do 
 
